### PR TITLE
Upgrade to Laravel 10

### PR DESCRIPTION
**Pull request by szepeviktor**
Just testing ...

### CODE REVIEW

**Comment by szepeviktor** [comment]
@iamgergo All test pass on L10. 🍏 
Please close this one.

**Comment by iamgergo** [comment]
@szepeviktor Could you update this for the stable L10, please?

**Comment by szepeviktor** [comment]
Will you run PHPUnit v9 tests?

**Comment by szepeviktor** [comment]
image

**Comment by iamgergo** [comment]
> Will you run PHPUnit v9 tests?

No, v10.

**Pull request merged**
