### PR TITLE
Fix dark/light mode logo in README

### PR DESCRIPTION
**Pull request by szepeviktor**
Docs: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

@adamlaki Please check other Cone repos.

### CODE REVIEW

**Comment by szepeviktor** [comment]
image

**Comment by adamlaki** [comment]
Finally, this looks so much more. Thank you Vikor, I will update some other repos!

**Comment by szepeviktor** [comment]
Maybe I've given a bad default images. Browsers without light/dark mode will use the light logo!

**Comment by adamlaki** [comment]
Yes, good point. Fixed it!

**Comment by szepeviktor** [comment]
I am so glad to contribute.

**Pull request merged**
