### PR TITLE
Handle unknown HTTP method in MediaController

### PR DESCRIPTION
**Pull request by szepeviktor**
This is not complete but a base to start with.

From https://github.com/conedevelopment/root/pull/165#issuecomment-1779378085

### CODE REVIEW

**Comment by iamgergo** [comment]
So, in the routes file only these 3 methods are allowed. But you're right, it's a good idea to have a fallback. Can you import the class please?

**Comment by szepeviktor** [comment]
> it's a good idea

It comes from phpstan.

**Comment by szepeviktor** [comment]
> Can you import the class please?

Done.
(I use FQCN in exception)

**Comment by szepeviktor** [comment]
Wait!
https://github.com/symfony/symfony/blob/3d078d158b895b10a9525bc56efd46715649491e/src/Symfony/Component/ErrorHandler/Tests/Exception/FlattenExceptionTest.php#L64

**Pull request merged**
