### PR TITLE
fix CS

### PR DESCRIPTION
**Pull request by szepeviktor**
easy review: https://github.com/conedevelopment/root/pull/190/files?diff=unified&w=1

### CODE REVIEW

**Comment by szepeviktor** [comment]
image

**Comment by szepeviktor** [comment]
@iamgergo Please rebuild assets.

**Comment by iamgergo** [comment]
can we change the linter to two spaces?

**Comment by szepeviktor** [comment]
> can we change the linter to two spaces?

I can't.
You can!

**Comment by szepeviktor** [comment]
I see two spaces not as a **contribution** but as doing harm.

**Pull request closed without merging**
